---
title: "TidyTuesday"
author: "Solal Chauquet"
date: "5/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TidyTuesday

```{r}
library(tidyverse)
library(ggplot2)
sessionInfo()
```

28/05/19: 
Wine ranking

```{r 28/05}
library(ggstance)
#wine <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv")

color = RColorBrewer::brewer.pal(3,'Blues')
lineplot = wine %>%
  group_by(country) %>%
  drop_na(country) %>%
  summarise(mean = mean(points), 
            SD = sd(points), 
            n = n()) %>%
  drop_na(SD) %>%
  arrange(mean) %>%
  mutate(signif = as.factor(ifelse(n>100,color[1],color[3])))

x= lineplot$country
lineplot$country = factor(lineplot$country, levels = x)
  
p = ggplot(lineplot, aes(y=country, x=mean, xmin=mean-SD, xmax=mean+SD, color= I(signif))) +
  geom_point() +
  geom_errorbarh() +
  ylab('') +
  xlab('Mean Review Score') +
  theme_light() +
  scale_color_discrete('Number of review:', labels= c('< 100 review', '> 100 review')) +
  labs(title = "Which country produce the best wine?",
       caption = "Source: WineEnthusiast") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.y  = element_text(size=8.5),
        panel.grid.major.x=element_blank(),
        panel.grid.minor.x=element_blank()) 
p
ggsave(p, filename = 'WineRanking.jpeg', device = 'jpeg', path = '/Users/s.chauquet/Documents/DataScience/TidyTuesday')
```

04/06/19:
Ramen Rating

```{r}
ramen <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-04/ramen_ratings.csv")
country_tp = ramen %>% group_by(country) %>% summarise(n=n()) %>% filter(n>50) %>% pull(country)

ramen_tp = ramen %>% group_by(country, style) %>% summarise(n=n(), rating = mean(stars, na.rm = T)) %>% filter(country %in% country_tp, rating > 3.3, n>10)

order = ramen %>% group_by(country) %>% summarise(n = n(), rating= mean(stars, na.rm=T)) %>% filter(n>50) %>% arrange(rating)


p = ggplot(ramen_tp, aes(y=factor(country, levels = order$country), x=rating)) +
  geom_point(aes(shape=style, color = country), size = 4) +
  xlab('Ranking') + ylab('') + labs(title = "What and where are the best Ramen?",
       caption = "The Ramen Rater") +
  scale_shape_discrete('Kind of Ramen') +
  scale_color_discrete(guide = F) +
  scale_x_continuous(breaks = seq(3.2, 4.3, 0.1)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(panel.grid.major.y = element_line(colour = "black"))

ggsave(p, filename = 'RamenRanking.jpeg', device = 'jpeg', path = '/Users/s.chauquet/Documents/DataScience/TidyTuesday')
```